### ISSUE TITLE
wimlib-imagex build failing: faccessat2==EPERM with default docker seccomp profile

### ISSUE THREAD

**Issue by glvnst** [backplane/conex#10]
The wimlib-imagex container build is broken. I suspect it's complicated.

```
/build #  make --trace --debug all-am
GNU Make 4.3
Built for x86_64-alpine-linux-musl
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'all-am' does not exist.
   File 'wimlib-imagex' does not exist.
     File 'programs/wimlib_imagex-imagex.o' does not exist.
       File 'programs/.dirstamp' does not exist.
      Must remake target 'programs/.dirstamp'.
Makefile:1305: target 'programs/.dirstamp' does not exist
build-aux/install-sh -c -d programs
make: /bin/bash: Operation not permitted
make: *** [Makefile:1305: programs/.dirstamp] Error 127
```

By running `strace make --trace --debug all-am`, we find:

```
faccessat2(AT_FDCWD, "/bin/sh", X_OK, AT_EACCESS) = -1 EPERM (Operation not permitted)
```

...which I think means we're checking "if the execute permission is enabled for any of the file owner, group, or other" on `/bin/sh` (it is, we're running it RN)

* <https://www.man7.org/linux/man-pages/man2/faccessat.2.html>
* <https://bugzilla.redhat.com/show_bug.cgi?id=1869030>
* <https://git.musl-libc.org/cgit/musl/commit/?id=55fb9a177316aa46c639d93dd0323d9a9a8c160c>
* <https://git.musl-libc.org/cgit/musl/commit/?id=9b7ed9702ce8925a5a947ad3bdbba126fe955aaf>

Here's my hand-wavey theory which isn't backed by actual data: there's a new syscall [`faccessat2`](https://www.man7.org/linux/man-pages/man2/faccessat.2.html), libc (incl. musl) have been updated to use it and for some reason it gets called before `exec` to check if you can `exec`. I'm wondering if the default docker seccomp profile has not yet been updated to account for this new syscall? I have no evidence.

I'm running this with "Docker 3.1.0", aka:

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

see also the linux version running in linuxkit / hyperkit / whatever:

```sh
$ docker run --rm -it --privileged --pid=host alpine:edge nsenter -t 1 -m -u -n -i cat /proc/version
Linux version 4.19.121-linuxkit (root@buildkitsandbox) (gcc version 9.2.0 (Alpine 9.2.0)) #1 SMP Tue Dec 1 17:50:32 UTC 2020
```

**Comment by glvnst** [comment]
Yep. Adding `--security-opt seccomp=unconfined` seems to fix it.

**Comment by glvnst** [comment]
https://github.com/google/or-tools/issues/2349 has a link to the alpine team tracking this issue: <https://gitlab.alpinelinux.org/alpine/aports/-/issues/12321>

And docker is tracking it here: https://github.com/moby/moby/pull/41381

**Comment by actualben** [comment]
resolved by docker updates on github runner infra
